<Project>
  <!-- Keeps restricted/test builds independent from caches created by another Windows identity. -->
  <PropertyGroup Condition="'$(UsageLoomIsolatedBuild)' == 'true'">
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\obj\**;$(MSBuildProjectDirectory)\bin\**</DefaultItemExcludes>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts\obj-isolated\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts\bin-isolated\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
